name: "Resource pack binding generator"
description: "Generates java bindings for Minecraft resource packs"
author: "solid-resourcepack"
branding:
  icon: "layers"
  color: "white"

inputs:
  gradle_task:
    description: "The Gradle task to execute"
    required: true
    default: "generatePackBindings"

  version:
    description: "Version of io.github.solid-resourcepack.binder"
    required: true
    default: "1.1.2"

  depth:
    description: "Depth of the model namespace to include"
    required: true
    default: "2"

  package:
    description: "Package name for generated classes"
    required: true

  classname:
    description: "Class name for the resulting enum"
    required: true
    default: "PackBindings"

  artifact_id:
    description: "Artifact ID for publication"
    required: true

  artifact_version:
    description: "Artifact version for publication"
    required: true

  namespaces:
    description: "Comma-separated list of namespaces"
    required: true

  should_publish:
    description: "Whether the generated enum should be published or not"
    required: true
    default: "false"

  repo_url:
    description: "Reposilite repository URL"
    required: false
    default: ""

  repo_user:
    description: "Reposilite username (GitHub Secret recommended)"
    required: false
    default: ""

  repo_password:
    description: "Reposilite password (GitHub Secret recommended)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout Repository to `pack` Directory
      uses: actions/checkout@v4
      with:
        path: pack
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - name: Set up Gradle
      run: chmod +x $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash

    - name: Execute Gradle Task and Publish
      run: |
        IFS=',' read -r -a NAMESPACE_ARRAY <<< "${{ inputs.namespaces }}"
        $GITHUB_ACTION_PATH/entrypoint.sh \
          "${{ inputs.gradle_task }}" \
          "${{ inputs.version }}" \
          "${{ inputs.depth }}" \
          "${{ inputs.package }}" \
          "${{ inputs.classname }}" \
          "${{ inputs.artifact_id }}" \
          "${{ inputs.artifact_version }}" \
          "${{ inputs.should_publish }}" \
          "${{ inputs.repo_url }}" \
          "${{ inputs.repo_user }}" \
          "${{ inputs.repo_password }}" \
          "${NAMESPACE_ARRAY[@]}"
      shell: bash
